FROM ubuntu:18.04
LABEL maintainer="MCL <c.y.lam@ljmu.ac.uk>"

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update && apt-get install -y python3
RUN apt-get update && apt-get install -y python3-pip



